In [18]:
import numpy as np

N = 4
A = (2 * np.eye(N) - np.eye(N, k=-1) - np.eye(N, k=1)+[1,2,3,4])
Q = np.zeros_like(A)     #nuloví matice
R = np.diag(np.ones(N))  #diagonální matice - jednotková

def GS(A):
    Q[:, 0] = A[:, 0]
    for k in range(1, N): 
        v = A[:, k]
        for l in range(0, k):
            q_l = Q[:, l]
            R[l, k] = (q_l.T @ A[:, k]) / (q_l.T @ q_l)
            v = v - R[l, k] * q_l
        R[k, k] = np.linalg.norm(v)
        Q[:, k] = v


    return Q,R

Q, R = GS(A)

for i in range (20):
    A = R@Q
    A = Q@R

print("Matice A:\n", A)
print("Matice Q:\n", Q)
print("Matice R:\n", R)
print("Q * R:\n", Q @ R)


Matice A:
 [[ 3.         -1.11750121  0.5919998   2.80068438]
 [ 0.         17.31000762  0.99865338  2.45802278]
 [ 1.          2.51250087 13.03461453  2.8286692 ]
 [ 1.          6.84000277  1.18938607  9.76927765]]
Matice Q:
 [[ 3.         -0.63636364 -0.98058252 -0.7398374 ]
 [ 0.          4.         -0.40776699 -0.95121951]
 [ 1.          0.45454545  3.27184466 -0.10569106]
 [ 1.          1.45454545 -0.33009709  2.32520325]]
Matice R:
 [[1.         0.54545455 1.45454545 1.90909091]
 [0.         4.3275019  0.60194175 1.25728155]
 [0.         0.         3.45568337 0.19105691]
 [0.         0.         0.         2.62105298]]
Q * R:
 [[ 3.         -1.11750121  0.5919998   2.80068438]
 [ 0.         17.31000762  0.99865338  2.45802278]
 [ 1.          2.51250087 13.03461453  2.8286692 ]
 [ 1.          6.84000277  1.18938607  9.76927765]]
